### ISSUE TITLE
catch-22: need an existing pad to be able to login and create one

### ISSUE THREAD

**Issue by thmo** [ether/ep_readonly_guest#2]
Unless I am missing something, the log-in knob is displayed only next to the "Read-Only Guest" entry in a pad's user list.

So, without at least a reference to an existing pad, it is not possible to log-in.

Would it be possible to put a log-in knob also on the front page?

And/or on the more or less empty page that is shown when one (being not logged in) tries to create a new pad, but isn't allowed to?

**Comment by rhansen** [comment]
Workaround until this is fixed: Manually visit `/ep_readonly_guest/login`

**Comment by rhansen** [comment]
I added a login button to the "permission denied" page in https://github.com/ether/ep_readonly_guest/commit/0f7a912a625ea0ed8238a91f65ba2fa94957a015 (ep_readonly_guest v1.0.12). However, Etherpad must be updated with https://github.com/ether/etherpad-lite/pull/4526 to see the new login button.

I could also add a login button to the front page, but I think that having one there is not valuable enough to be worth the effort. If someone has a compelling use case and would like it added to the front page, please speak up and I will reopen this issue.
